### ISSUE TITLE
Shortcode and/or CK5 Icon picker interaction problem

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/ucb_migration_shortcodes#21]
Not sure if this is a problem just with the shortcode module or if it's an issue with the way the CK5 iconpicker plugin interacts with this type of shortcode.  But when you have a button with an icon inside of it we end up with broken HTML.  

example : 

` [button url="/on-demand" color="gold"]Resources you can use right now [icon shape="fa-wrench" /] [/button]`

ends up looking like : 

<img width="686" alt="Screenshot 2024-05-01 at 10 42 58 AM" src="https://github.com/CuBoulder/tiamat-theme/assets/12704433/79939725-a1dc-44aa-ad16-2cb022ac1876">

**Comment by patrickbrown-io** [comment]
Related :: https://github.com/CuBoulder/ucb_migration_shortcodes/issues/23
