### ISSUE TITLE
Google Calendar Shortcode 

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/ucb_migration_shortcodes#27]
Found during migration

`[googlecalendar]https://calendar.google.com/calendar/embed?height=600&wkst=1&bgcolor=%23FFFFFF&src=ffte73qsqer0marq8d69q9lbvc%40group.calendar.google.com&color=%23853104&src=colorado.edu_0mdo7383mhiieauu0spp6vrm0k%40group.calendar.google.com&color=%2342104A&ctz=America%2FDenver[/googlecalendar]`

Generates a `Not a valid Google calendar.` message but works in the live site.  Any ideas what's wrong with this calendar format?

**Comment by jacob-korf** [comment]
Looks like this is an issue with Google changing the format of the calendar URL.
<img width="600" alt="Screenshot 2024-06-20 at 3 04 46 PM" src="https://github.com/CuBoulder/ucb_migration_shortcodes/assets/56124082/4b7e3948-265a-4819-bea3-245f284787a5">
As seen in this image, the beginning of the URL in the example of what was not working does not fit with the old version of the migration shortcode. With the update being added for #38, this problem should be resolved.
