### ISSUE TITLE
Anchors Shortcode: Info

### ISSUE THREAD

**Issue by jnicholCU** [CuBoulder/ucb_migration_shortcodes#8]
By providing a jquery selector, anchors are created and a list of links to those anchors is inserted in place of the shortcode. For example [anchors selector="#content h2" title="On this page:" /] will add anchors to all h2 headings within the .content element, and create a list of links to those anchors and title that list with "On this page:".

**Comment by jcsparks** [comment]
Using a contrib anchor solution for CK5 now.
